[workspace]
members = [
    "bitfield-assertion",
    "bitfield-assertion/src/bitfield",
    "bitfield-assertion/src/impl",
    "callable-types",
    "function-epilogue",
    "integer-match",
    "readonly-fields",
    "unit-type-parameters",
]
