[package]
name = "case-study-bitfield-assertion"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
bitfield = { path = "src/bitfield" }
